made cleanup of file structure. added some scripting issues to improve debbuging, rebuilt Ccharacter class

diff --git a/Debug b/Debug
--- a/Debug
+++ b/Debug
@@ -15,6 +15,10 @@ else
 fi
 
 if [ -z "$*" ]; then
+    if [ ! -x "./main" ]; then
+        echo "Couldn't find executable to debug."
+        exit 1
+    fi
     echo "Param not given! Debugging main."
     if [ -z "$insight" ]; then
 	gdb ./main
@@ -22,6 +26,10 @@ if [ -z "$*" ]; then
 	insight ./main
     fi
 else
+    if [ ! -x "$*" ]; then
+        echo "Couldn't find executable to debug."
+        exit 1
+    fi
     echo "Debugging $*"
     if [ -z "$insight" ]; then
 	gdb ./$*
